# Config file when robot is mounted on vention stand

room_path:
  description: "Base path for the room"
  type: "path"
  values: "tv_world/body_2.obj"

table_path:
  description: "Base path for the table"
  type: "path"
  values: "tv_world/square_table.obj"

table_spawn_pose:
  description: "Position of the table in the room"
  type: "pose"
  values: [0.6, 0.45, -0.66, 0, 0, 0, 1]

spawn_tv:
  description: "Spawn the tv in the room"
  type: "bool"
  values: true

tv_base_pose:
  description: "Pose of the whole tv apparatus"
  type: "pose"
  values: [1, 0.8, -0.66, 0, 0, 0, 1]

spawn_social:
  description: "Spawn a social partner in the room"
  type: "bool"
  values: true

social_base_pose:
  description: "Base pose of the social partner"
  type: "pose"
  values: [1.2, 0.73, -0.66, 0, 0, 0.5, 0.8660254]

social_mesh_path:
  description: "Path to the social partner mesh"
  type: "path"
  values: "tv_world/human_looking_right.obj"

robot_spawn_side:
  description: "Spawn side of the robot (true = right, false = left)"
  type: "bool"
  values: true

robot_holder_pose:
  description: "Pose of the robot holder"
  type: "pose"
  values: [0.0, 0.0, -0.34, 0, 0, 0, 1]

wheelchair_pose:
  description: "Pose of the wheelchair"
  type: "pose"
  values: [-0.2, 0.45, -0.06, 0, 0, 0, 1]

user_head_pose:
  description: "Pose of the user head"
  type: "pose"
  values: [-0.4, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

user_eyes_relative_pose:
  description: "Pose of the user eyes"
  type: "pose"
  values: [0.0, 0.1, 0.1, 0.0, 0.0, 0.0, 1]

table_pose:
  description: "Pose of the table used for sampling"
  type: "pose"
  values: [0.5, 0.45, 0.15, 0, 0, 0, 1]
  # more x is forward away from the robot

plate_default_pose:
  description: "Default pose of the plate"
  type: "pose"
  values: [0.4, 0.3, 0.17, 0, 0, 0, 1]

utensil_inside_mount:
  description: "Pose of the utensil inside the mount"
  type: "pose"
  values: [0.242, -0.077, 0.07, -1, 0, 0, 0]

drink_default_pose:
  description: "Default pose of the drink"
  type: "pose"
  values: [0.6, 0.3, 0.35, 0, 0.7071, 0.7071, 0]

drink_staging_pos:
  description: "Staging position of the drink"
  type: "joint_positions"
  # values: [-2.5860902733967808, -1.105096803823792, -1.0315333702969696, -1.3979449215077393, -0.7852325147776451, -0.8370922506847585, -2.7182634909296315]
  # values: [-2.613708681215308, -0.9017579053460443, -0.9960620769089157, -1.2661829309009238, -0.832709162582267, -0.9714922346688137, -2.940585756029876]
  values: [-2.7735988378314134, -0.8968768669006932, -0.7212871908361091, -1.019248071874871, -1.0616228119480924, -1.3347197444542265, -2.9629514892876214]
  # values: [-2.7735988378314134, -0.886988657767636, -0.7459052994952011, -0.9787181720636453, -1.0410412101589737, -1.3374020632510817, -3.018077279765413]
  # values: [-2.8147331790815286, -0.8506252792702531, -0.6638130367116478, -0.9059021223451302, -1.0991164072710515, -1.3907797975486722, -3.0815421054508567]

drink_default_post_grasp_pose:
  description: "Pose of the drink after grasping"
  type: "pose"
  values: [0.56, 0.3, 0.5, 0, 0.7071, 0.7071, 0]

before_transfer_pos:
  description: "Config of the robot before transfer"
  type: "joint_positions"
  values: [-2.86554642, -1.61951779, -2.60986085, -1.37302839, 1.11779249, -1.18028264, 2.05515862]

above_plate_pos:
  description: "Config of the robot above the plate"
  type: "joint_positions"
  values: [-2.86495014, -1.61460533, -2.6115943, -1.37673391, 1.11842806, -1.17904586, -2.6957422]

before_transfer_pose:
  description: "Pose of the robot before transfer"
  type: "pose"
  values: [0.504, 0.303, 0.529, 0.0, 0.707, 0.707, 0]

